PREFIX akgs: <https://deborrrrrah.github.io/ns#> 
PREFIX akgr: <https://deborrrrrah.github.io/resource/> 

SELECT ?product ?variant
WHERE
{ akgr:Paragon_Technology_And_Innovation akgs:owns ?product . ?product akgs:brand "Emina" . ?product akgs:usage "Mata" . ?product akgs:variant ?variant .}  
