PREFIX akgs: <https://deborrrrrah.github.io/ns#> 
PREFIX akgr: <https://deborrrrrah.github.io/resource/> 

DESCRIBE ?product
WHERE
{ akgr:Sariayu akgs:memproduksi ?product . ?product akgs:penggunaan "Wajah" .}  
