PREFIX akgs: <https://deborrrrrah.github.io/ns#> 
PREFIX akgr: <https://deborrrrrah.github.io/resource/> 

SELECT ?product ?variant
WHERE
{?product akgs:brand akgr:Emina . ?product akgs:variant ?variant . ?product akgs:usage "Wajah" .}  
