PREFIX akgs: <https://deborrrrrah.github.io/ns#> 
PREFIX akgr: <https://deborrrrrah.github.io/resource/> 

DESCRIBE ?product
WHERE
{ akgr:Sariayu akgs:produces ?product . ?product akgs:usage "Wajah" .}  
