PREFIX akgs: <https://deborrrrrah.github.io/ns#> 
PREFIX akgr: <https://deborrrrrah.github.io/resource/> 

SELECT ?brand ?product
WHERE
{ ?brand akgs:produces ?product . ?product akgs:usage "Bibir" .}  
